### ISSUE TITLE
Chrome browser found errors when I used this code

### ISSUE THREAD

**Issue by MJ-sfo** [jaketrent/jaketrent-blog#12]
Chrome did not recognize 'radio' In:
  <input type="radio"    
Is that the type of data you are trying to push to Child?  I tried to change to 'object'

Chrome also did not recognize 'props' in:
          <input type="object" value={props.value} name={props.name} />
          {props.label}
Not clear from your blog what the Child component needs to do to read/receive this data.

**Comment by jaketrent** [comment]
Not sure what to do about this at this point.  Closing for now.
